#!/bin/bash -eu
rm -rf /tmp/testdepot
mkdir /tmp/testdepot
rm -rf /tmp/test
mkdir /tmp/test
cd /tmp/test
export JULIA_DEPOT_PATH=/tmp/testdepot 
export JULIA_PKG_SERVER_REGISTRY_PREFERANCE=eager
git clone https://github.com/ufechner7/KiteModels.jl.git
cd KiteModels.jl
git checkout compact
rm -rf .git
rm -rf .github
rm -rf docs
rm -rf mwes
cd bin
./create_sys_image --update
cd ..
du -h .
